version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: ${{secrets.GH_USERNAME}}
    password: ${{secrets.GH_TOKEN}}
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    registries:
      - github
    
    schedule:
      interval: "daily"
    allow:
      # Allow updates for Lodash
      - dependency-name: "ets-contracts"
