 version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
     allow:
      - dependency-name: "ets-contracts"
    ignore:
      - dependency-name: "ets-contracts"
        update-types: ["version-update:semver-majar"]
