version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: ${{secrets.GH_USERNAME}}
    password: ${{secrets.GH_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "ets-contracts"
