# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Checkout ets-contracts
      uses: actions/checkout@master
      with: 
            repository: Applied-Blockchain-Lab/ets-contracts
            token: ${{ secrets.TOKEN }}
            path: ./ets-contracts
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
    - name: Generate json
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
           cd ./ets-contracts
           npm install
           echo ${{ secrets.ADDRESS }} > .secret
           npx hardhat compile
           readarray -t Arr < README.md
           cd ..
           rm ./src/configs/contract.config.js
           echo "import {schema} from '../schema/EventTicketingSystem.js';" > ./src/configs/contract.config.js
           echo "const ${Arr[13]};" >> ./src/configs/contract.config.js
           echo "const ${Arr[15]};" >> ./src/configs/contract.config.js
           echo 'const IPFS_GATEWAY_PROVIDER_URL = "https://nftstorage.link/ipfs/";' >> ./src/configs/contract.config.js
           echo "const ABI = schema.abi;" >> ./src/configs/contract.config.js
           echo "export { IPFS_GATEWAY_PROVIDER_URL,AVALANCHE_TESTNET_API,EVENT_TICKETING_SYSTEM_CONTRACT_ADDRESS,ABI};" >> ./src/configs/contract.config.js
 
     

        
    - name: Copy json file
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
          rm ./src/schema/EventTicketingSystem.js
          echo export let schema = > ./src/schema/EventTicketingSystem.js
          echo $(cat ./ets-contracts/artifacts/contracts/EventTicketingSystem.sol/EventTicketingSystem.json) >> ./src/schema/EventTicketingSystem.js
    
    - name: Commit
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
            rm -r ets-contracts
            git add * 
            git config user.name github-actions
            git config user.email github-actions@github.com
            git diff-index --quiet HEAD || git commit -m "${{ github.event.commits[0].message }} + Fetch json and env from contracts"
            git push
  
  

